/**
 * Abstract, tool-agnostic UI schema generated by core pipeline agents
 * (e.g., UI Generation, Prototype Generation).
 * Shared between the former Figma pipeline and the new HTML renderer.
 */

export type AgnosticComponentType = 'button' | 'container' | 'text' | 'image' | 'input' | 'link' | 'list' | 'nav';

export interface AgnosticStyle {
  backgroundColor?: string;
  color?: string;
  borderRadius?: number;
  borderColor?: string;
  borderWidth?: number;
  padding?: number | [number, number, number, number];
  margin?: number | [number, number, number, number];
  gap?: number;
  width?: number | string;
  height?: number | string;
  fontSize?: number;
  fontWeight?: number | string;
  textAlign?: 'left' | 'center' | 'right';
  layout?: 'row' | 'column';
  overflow?: 'hidden' | 'scroll' | 'auto' | 'visible';
  opacity?: number;
  cursor?: string;
  position?: 'static' | 'relative' | 'absolute' | 'fixed' | 'sticky';
}

export interface AgnosticComponent {
  id: string;
  type: AgnosticComponentType;
  name: string;
  text?: string;
  href?: string;
  src?: string;
  alt?: string;
  placeholder?: string;
  ariaLabel?: string;
  role?: string;
  style?: AgnosticStyle;
  children?: AgnosticComponent[];
  events?: Record<string, string>;
}

export interface AgnosticScreen {
  id: string;
  title: string;
  route?: string;
  components: AgnosticComponent[];
  meta?: {
    description?: string;
    viewport?: string;
  };
}

export interface AgnosticPrototype {
  id: string;
  title: string;
  screens: AgnosticScreen[];
  transitions: PrototypeTransition[];
}

export interface PrototypeTransition {
  fromScreenId: string;
  toScreenId: string;
  trigger: 'click' | 'hover' | 'timer' | 'scroll';
  targetElementId?: string;
  animation?: 'fade' | 'slide-left' | 'slide-right' | 'slide-up' | 'slide-down' | 'none';
  duration?: number;
}
