/**
 * Abstract, tool-agnostic UI schema generated by core pipeline agents
 * (e.g., UI Generation, Prototype Generation).
 * This schema does not know about Figma's specific data structures.
 */

export type AgnosticComponentType = 'button' | 'container' | 'text' | 'image' | 'input';

export interface AgnosticStyle {
  backgroundColor?: string; // hex string
  color?: string; // hex string
  borderRadius?: number;
  padding?: number | [number, number, number, number]; // top, right, bottom, left
  gap?: number;
  width?: number | 'fill' | 'hug';
  height?: number | 'fill' | 'hug';
  fontSize?: number;
  textAlign?: 'left' | 'center' | 'right';
  layout?: 'row' | 'column';
}

export interface AgnosticComponent {
  id: string;
  type: AgnosticComponentType;
  name: string;
  text?: string; // Used for button labels, text elements
  style?: AgnosticStyle;
  children?: AgnosticComponent[];
}
